languageCode = "ru-ru"
title = "Health&Help Secret Santa"

[params]
    STRIPE_PUBLISHABLE_KEY = "pk_live_0rEgoe4LSNQL22eihCHkXTr70025zna97b"
    STRIPE_PRICE_5_USD = "price_1I05VOIjit1s7RiHLrA7mwod"
    STRIPE_PRICE_10_USD = "price_1I0AjfIjit1s7RiHXPH6fPj1"
    STRIPE_PRICE_25_USD = "price_1I0AjuIjit1s7RiHTa1TVk3R"
    STRIPE_PRICE_50_USD = "price_1I0Ak6Ijit1s7RiHvefKzTmx"
    STRIPE_PRICE_100_USD = "price_1I0AkHIjit1s7RiHWkeku1AX"
