[context.production.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"

[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run start"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
